# Generated by Django 5.0 on 2024-09-25 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationhistory',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conversation.contact'),
        ),
        migrations.AlterField(
            model_name='conversationhistory',
            name='user_virtual_phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conversation.uservirtualphonenumber'),
        ),
    ]
