# Generated by Django 5.0 on 2024-09-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversationhistory_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservirtualphonenumber',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
