# Generated by Django 5.0 on 2024-09-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_parties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpeechToText',
            new_name='ThirdParty',
        ),
        migrations.DeleteModel(
            name='ConversationAnalyser',
        ),
    ]
